server:
  port: 9191

spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri:
          lb://USER-SERVICE
        predicates:
        - Path=/users/**
      - id: DEPARTMENT-SERVICE
        uri:
          lb://DEPARTMENT-SERVICE
        predicates:
        - Path=/department/**
#
#spring.cloud.config.discovery.enabled=false


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost   